function stData = getEmailData()

stData = struct('E_mail', 'ulrik.kowalk@jade-hs.de', ...
    'SMTP_Server','mail.jade-hs.de', ...
    'SMTP_Username','ul1021@hs-woe.de', ...
    'SMTP_Password','M1ch@3l!');

end